source: https://github.com/julioborgesigt/representacoes

features:
  - node lts
  - mysql

nginx:
  root: public_html/public
  passenger:
    enabled: "on"
    app_start_command: env PORT=$PORT npm start
    env_var_list:
      - NODE_ENV=production
      - DB_HOST=sao.domcloud.co
      - DB_USER=nome-do-seu-usuario
      - DB_PASS=sua-senha-domcloud
      - DB_NAME=nome_do_banco
      - SESSION_SECRET=cole_aqui_uma_string_aleatoria_longa
      - ADMIN_SENHA=Admin@123

commands:
  - git pull origin main
  - npm install
  - mkdir -p tmp
  - touch tmp/restart.txt
