source: https://github.com/julioborgesigt/representacoes

features:
  - node lts
  - mysql

nginx:
  passenger:
    enabled: "on"
    app_start_command: env PORT=$PORT npm start
    env_var_list:
      - NODE_ENV=production
      - DB_HOST=sao.domcloud.co
      - DB_USER=representacoes
      - DB_PASS=PfA52e+dF37_-hBP3x
      - DB_NAME=representacoes_db
      - SESSION_SECRET=143043b60c80f7a1a13079ffd10b0b7e7ca5d390517aadc18
      - ADMIN_SENHA=1a2b3cd4

commands:
  - npm install
  - mkdir -p tmp
  - touch tmp/restart.txt
